/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import Entidade.User;

/**
 *
 * @author victo
 */
public class Home extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form Home
     */
    public Home(User user) {
        initComponents();
        this.user = user;
    }

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkCadastro = new javax.swing.JLabel();
        linkPesquisa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        menu_pesquisa = new javax.swing.JMenu();
        menuItemPesqUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Home");
        setPreferredSize(new java.awt.Dimension(500, 400));

        linkCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar-usuario _64.png"))); // NOI18N
        linkCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        linkCadastro.setPreferredSize(new java.awt.Dimension(64, 64));
        linkCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkCadastroMouseClicked(evt);
            }
        });

        linkPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar-usuario.png"))); // NOI18N
        linkPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        linkPesquisa.setPreferredSize(new java.awt.Dimension(64, 64));
        linkPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkPesquisarMouseClicked(evt);
            }
        });

        menu_cadastro.setText("Cadastro");

        menuItemCadUsuario.setText("Usuário");
        menuItemCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemCadUsuarioMousePressed(evt);
            }
        });
        menu_cadastro.add(menuItemCadUsuario);

        jMenuBar1.add(menu_cadastro);

        menu_pesquisa.setText("Pesquisa");

        menuItemPesqUsuario.setText("jMenuItem1");
        menuItemPesqUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemPesqUsuarioMousePressed(evt);
            }
        });
        menu_pesquisa.add(menuItemPesqUsuario);

        jMenuBar1.add(menu_pesquisa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(linkCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_linkCadastroMouseClicked

    private void linkPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkPesquisarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_linkPesquisarMouseClicked

    private void menuItemCadUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCadUsuarioMousePressed

    private void menuItemPesqUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPesqUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPesqUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel linkCadastro;
    private javax.swing.JLabel linkPesquisa;
    private javax.swing.JMenuItem menuItemCadUsuario;
    private javax.swing.JMenuItem menuItemPesqUsuario;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_pesquisa;
    // End of variables declaration//GEN-END:variables
}
