/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela.funcionario;

import entidade.Funcionario;
import entidadeDao.FuncionarioDao;
import entidadeDao.FuncionarioDaoImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author victor.rocha
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    private Funcionario funcionario;
    private FuncionarioDao funcionarioDao = new FuncionarioDaoImpl();
    private int id;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
    }

    public CadastroFuncionario(Funcionario funcionario) {
        initComponents();
        this.funcionario = funcionario;
        varNomeFuncionario.setText(funcionario.getNome());
        varSobrenomeFuncionario.setText(funcionario.getSobrenome());
        varCpfFuncionario.setText(Long.toString(funcionario.getCpf()));
        varEnderecoFuncionario.setText(funcionario.getEndereco());
        varEmailFuncionario.setText(funcionario.getEmail());
        varIdadeFuncionario.setText(Integer.toString(funcionario.getIdade()));
        varTelefoneFuncionario.setText(Long.toString(funcionario.getTelefone()));
        varSenhaFuncionario.setText(funcionario.getSenha());
        varCargoFuncionario.setText(funcionario.getCargo());
        id = funcionario.getId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varEnderecoFuncionario = new javax.swing.JTextField();
        lbEnderecoFuncionario = new javax.swing.JLabel();
        lbTituloCadFuncionario = new javax.swing.JLabel();
        varIdadeFuncionario = new javax.swing.JTextField();
        varNomeFuncionario = new javax.swing.JTextField();
        lbIdadeFuncionario = new javax.swing.JLabel();
        lbSenhaFuncionario = new javax.swing.JLabel();
        lbNomeFuncionario = new javax.swing.JLabel();
        varSobrenomeFuncionario = new javax.swing.JTextField();
        varSenhaFuncionario = new javax.swing.JPasswordField();
        lbSobrenomeFuncionario = new javax.swing.JLabel();
        varCpfFuncionario = new javax.swing.JTextField();
        lbTelefoneFuncionario = new javax.swing.JLabel();
        varCargoFuncionario = new javax.swing.JTextField();
        lbPesoFuncionario = new javax.swing.JLabel();
        varTelefoneFuncionario = new javax.swing.JTextField();
        lbCargoFuncionario = new javax.swing.JLabel();
        varEmailFuncionario = new javax.swing.JTextField();
        lbEmailFuncionario = new javax.swing.JLabel();
        btCadastroFuncionario = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de funcionário");

        lbEnderecoFuncionario.setText("Endereço:");

        lbTituloCadFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTituloCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCadFuncionario.setText("Cadastro de Funcionário");
        lbTituloCadFuncionario.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        lbIdadeFuncionario.setText("Idade:");

        lbSenhaFuncionario.setText("Senha:");

        lbNomeFuncionario.setText("Nome:");
        lbNomeFuncionario.setToolTipText("");

        lbSobrenomeFuncionario.setText("Sobrenome:");

        lbTelefoneFuncionario.setText("Telefone:");

        lbPesoFuncionario.setText("CPF:");

        lbCargoFuncionario.setText("Cargo:");

        lbEmailFuncionario.setText("E-mail:");

        btCadastroFuncionario.setText("Salvar");
        btCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroFuncionarioActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addGap(42, 42, 42)
                .addComponent(btCadastroFuncionario)
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(varEmailFuncionario))
                                .addComponent(lbNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(varEnderecoFuncionario))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbSobrenomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(varSobrenomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTelefoneFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(lbSenhaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCargoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbPesoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(varCpfFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(varTelefoneFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(varCargoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(varSenhaFuncionario)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(varNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(55, Short.MAX_VALUE))
                .addComponent(lbTituloCadFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastroFuncionario)
                    .addComponent(btVoltar))
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lbTituloCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNomeFuncionario)
                        .addComponent(lbPesoFuncionario)
                        .addComponent(varNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSobrenomeFuncionario)
                        .addComponent(lbCargoFuncionario)
                        .addComponent(varSobrenomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEmailFuncionario)
                        .addComponent(lbTelefoneFuncionario)
                        .addComponent(varEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEnderecoFuncionario)
                        .addComponent(varEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSenhaFuncionario)
                        .addComponent(varSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbIdadeFuncionario)
                        .addComponent(varIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        new HomeFuncionarioLogado().setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroFuncionarioActionPerformed
        if (funcionario == null) {
            funcionario = new Funcionario();
            funcionario.setNome(varNomeFuncionario.getText().trim());
            funcionario.setSobrenome(varSobrenomeFuncionario.getText().trim());
            funcionario.setCpf(Long.parseLong(varCpfFuncionario.getText().trim()));
            funcionario.setEndereco(varEnderecoFuncionario.getText().trim());
            funcionario.setEmail(varEmailFuncionario.getText().trim());
            funcionario.setIdade(Integer.parseInt(varIdadeFuncionario.getText().trim()));
            funcionario.setTelefone(Long.parseLong(varTelefoneFuncionario.getText().trim()));
            funcionario.setCargo(varCargoFuncionario.getText().trim());
            funcionario.setSenha(String.valueOf(varSenhaFuncionario.getPassword()));
        } else {
            funcionario.setNome(varNomeFuncionario.getText().trim());
            funcionario.setSobrenome(varSobrenomeFuncionario.getText().trim());
            funcionario.setCpf(Long.parseLong(varCpfFuncionario.getText().trim()));
            funcionario.setEndereco(varEnderecoFuncionario.getText().trim());
            funcionario.setEmail(varEmailFuncionario.getText().trim());
            funcionario.setIdade(Integer.parseInt(varIdadeFuncionario.getText().trim()));
            funcionario.setTelefone(Long.parseLong(varTelefoneFuncionario.getText().trim()));
            funcionario.setSenha(String.valueOf(varSenhaFuncionario.getPassword()));
            funcionario.setCargo(varCargoFuncionario.getText().trim());
            funcionario.setId(id);
        }
        try {
            if (funcionario.getId() == null) {
                funcionarioDao.salvar(funcionario);
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!!");
            } else {
                funcionarioDao.alterar(funcionario);
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!!");
            }
            new HomeFuncionarioLogado().setVisible(true);
            dispose();
        } catch (Exception e) {
            System.out.println("Erro ao salvar ou alterar os dados do funcionário " + e.getMessage());
        }
    }//GEN-LAST:event_btCadastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroFuncionario;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel lbCargoFuncionario;
    private javax.swing.JLabel lbEmailFuncionario;
    private javax.swing.JLabel lbEnderecoFuncionario;
    private javax.swing.JLabel lbIdadeFuncionario;
    private javax.swing.JLabel lbNomeFuncionario;
    private javax.swing.JLabel lbPesoFuncionario;
    private javax.swing.JLabel lbSenhaFuncionario;
    private javax.swing.JLabel lbSobrenomeFuncionario;
    private javax.swing.JLabel lbTelefoneFuncionario;
    private javax.swing.JLabel lbTituloCadFuncionario;
    private javax.swing.JTextField varCargoFuncionario;
    private javax.swing.JTextField varCpfFuncionario;
    private javax.swing.JTextField varEmailFuncionario;
    private javax.swing.JTextField varEnderecoFuncionario;
    private javax.swing.JTextField varIdadeFuncionario;
    private javax.swing.JTextField varNomeFuncionario;
    private javax.swing.JPasswordField varSenhaFuncionario;
    private javax.swing.JTextField varSobrenomeFuncionario;
    private javax.swing.JTextField varTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
